from datetime import datetime

class Timestamp:
    def to_pydatetime(self) -> datetime: ...

class ExchangeCalendar:
    def is_session(self, date: str) -> bool: ...
    def session_open(self, session: str) -> Timestamp: ...
    def session_close(self, session: str) -> Timestamp: ...
