"""local paper portfolio and execution

Revision ID: 0008_m3_paper
Revises: 0007_m2_decisions
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0008_m3_paper"
down_revision: str | Sequence[str] | None = "0007_m2_decisions"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_runs",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("initial_cash", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("cash", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("fees", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("fee_bps", sa.Numeric(precision=16, scale=6), nullable=False),
        sa.Column("slippage_bps", sa.Numeric(precision=16, scale=6), nullable=False),
        sa.Column("dataset", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dataset_hash", sa.String(length=64), nullable=False),
        sa.Column("step", sa.BigInteger(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "mode = 'REPLAY' AND status IN ('READY','RUNNING','COMPLETED')",
            name="ck_paper_run_mode",
        ),
        sa.CheckConstraint(
            "cash >= 0 AND initial_cash > 0 AND fees >= 0 AND step >= 0", name="ck_paper_run_money"
        ),
        sa.CheckConstraint(
            "fee_bps BETWEEN 0 AND 100 AND slippage_bps BETWEEN 0 AND 100",
            name="ck_paper_run_costs",
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "paper_events",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=8), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["paper_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "paper_marks",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("price", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("price > 0", name="ck_paper_marks_price"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["paper_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "symbol"),
    )
    op.create_table(
        "portfolio_snapshots",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("step", sa.BigInteger(), nullable=False),
        sa.Column("cash", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("market_value", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("equity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("total_pnl", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("fees", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "equity = cash + market_value AND cash >= 0", name="ck_portfolio_snapshot_equity"
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["paper_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "step"),
    )
    op.create_table(
        "positions",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("average_price", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("quantity >= 0 AND average_price >= 0", name="ck_positions_long_only"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["paper_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "symbol"),
    )
    op.create_table(
        "system_controls",
        sa.Column("control_id", sa.BigInteger(), nullable=False),
        sa.Column("active_run_id", sa.Uuid(), nullable=True),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("control_id = 1", name="ck_controls_singleton"),
        sa.ForeignKeyConstraint(
            ["active_run_id"],
            ["paper_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("control_id"),
    )
    op.create_table(
        "paper_orders",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("signal_id", sa.Uuid(), nullable=False),
        sa.Column("risk_decision_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idempotency_key", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=128), nullable=False),
        sa.CheckConstraint(
            "side IN ('BUY','SELL') AND status IN ('FILLED','REJECTED') AND quantity >= 0",
            name="ck_paper_orders_state",
        ),
        sa.ForeignKeyConstraint(
            ["risk_decision_id"],
            ["risk_decisions.decision_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["paper_runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.signal_id"],
        ),
        sa.PrimaryKeyConstraint("order_id"),
        sa.UniqueConstraint("idempotency_key"),
        sa.UniqueConstraint("run_id", "risk_decision_id", name="uq_paper_order_risk"),
    )
    op.create_table(
        "paper_fills",
        sa.Column("fill_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("price", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("reference_price", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("fee", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("slippage", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "price > 0 AND reference_price > 0 AND quantity > 0 AND fee >= 0 AND slippage >= 0",
            name="ck_paper_fills_money",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["paper_orders.order_id"],
        ),
        sa.PrimaryKeyConstraint("fill_id"),
        sa.UniqueConstraint("order_id"),
    )
    op.create_table(
        "paper_outcomes",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("risk_decision_id", sa.Uuid(), nullable=False),
        sa.Column("signal_id", sa.Uuid(), nullable=False),
        sa.Column("execution_candle_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=128), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_candle_id"],
            ["candles.candle_id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["paper_orders.order_id"],
        ),
        sa.ForeignKeyConstraint(
            ["risk_decision_id"],
            ["risk_decisions.decision_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["paper_runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.signal_id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "risk_decision_id"),
    )
    op.execute(
        "INSERT INTO system_controls (control_id, paused, updated_at) "
        "VALUES (1, false, CURRENT_TIMESTAMP)"
    )


def downgrade() -> None:
    if op.get_bind().scalar(sa.text("SELECT EXISTS (SELECT 1 FROM paper_runs)")):
        raise RuntimeError("paper_data_present: backup and explicit recovery plan required")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("paper_outcomes")
    op.drop_table("paper_fills")
    op.drop_table("paper_orders")
    op.drop_table("system_controls")
    op.drop_table("positions")
    op.drop_table("portfolio_snapshots")
    op.drop_table("paper_marks")
    op.drop_table("paper_events")
    op.drop_table("paper_runs")
    # ### end Alembic commands ###
