"""m1_5_market_data

Revision ID: 23a618741eb9
Revises: a6634ae4e630
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "23a618741eb9"
down_revision: str | Sequence[str] | None = "a6634ae4e630"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candles", sa.Column("symbol", sa.String(length=16), server_default="TEST", nullable=False)
    )
    op.add_column(
        "candles", sa.Column("timeframe", sa.String(length=16), server_default="1h", nullable=False)
    )
    op.add_column(
        "candles",
        sa.Column("provider", sa.String(length=32), server_default="simulator", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("candles", "provider")
    op.drop_column("candles", "timeframe")
    op.drop_column("candles", "symbol")
    # ### end Alembic commands ###
