"""nullable_fee

Revision ID: 9621f2ecf977
Revises: 888888888888
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9621f2ecf977'
down_revision: str | Sequence[str] | None = '888888888888'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('broker_fills', 'fee',
               existing_type=sa.NUMERIC(precision=28, scale=10),
               nullable=True)
    op.alter_column('paper_fills', 'fee',
               existing_type=sa.NUMERIC(precision=28, scale=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paper_fills', 'fee',
               existing_type=sa.NUMERIC(precision=28, scale=10),
               nullable=False)
    op.alter_column('broker_fills', 'fee',
               existing_type=sa.NUMERIC(precision=28, scale=10),
               nullable=False)
    # ### end Alembic commands ###
