"""m2_strategy_risk

Revision ID: a6634ae4e630
Revises: 0002_m1
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a6634ae4e630"
down_revision: str | Sequence[str] | None = "0002_m1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signals",
        sa.Column("signal_id", sa.Uuid(), nullable=False),
        sa.Column("candle_id", sa.Uuid(), nullable=False),
        sa.Column("stream_id", sa.Uuid(), nullable=False),
        sa.Column("strategy_version", sa.String(length=64), nullable=False),
        sa.Column("signal_type", sa.String(length=16), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("signal_type IN ('BUY', 'SELL', 'HOLD')", name="ck_signals_type"),
        sa.ForeignKeyConstraint(
            ["candle_id"],
            ["candles.candle_id"],
        ),
        sa.PrimaryKeyConstraint("signal_id"),
        sa.UniqueConstraint("candle_id", "strategy_version", name="uq_signals_candle_strategy"),
    )
    op.create_table(
        "risk_decisions",
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("signal_id", sa.Uuid(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("decision IN ('APPROVED', 'REJECTED')", name="ck_risk_decisions_type"),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.signal_id"],
        ),
        sa.PrimaryKeyConstraint("decision_id"),
        sa.UniqueConstraint("signal_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("risk_decisions")
    op.drop_table("signals")
    # ### end Alembic commands ###
