"""fractional_quantities

Revision ID: cbec58d3efff
Revises: db6f20ef0e19
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cbec58d3efff'
down_revision: str | Sequence[str] | None = 'db6f20ef0e19'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paper_fills', 'quantity',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=28, scale=10),
               existing_nullable=False)
    op.alter_column('paper_orders', 'quantity',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=28, scale=10),
               existing_nullable=False)
    op.alter_column('paper_orders', 'filled_quantity',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=28, scale=10),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('positions', 'quantity',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=28, scale=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    
    # Block downgrade if there's fractional data to avoid silent loss
    tables_to_check = ['paper_orders', 'paper_fills', 'positions']
    for table in tables_to_check:
        res = conn.execute(sa.text(f"SELECT COUNT(*) FROM {table} WHERE quantity != TRUNC(quantity)")).scalar()
        if res and res > 0:
            raise ValueError(f"Cannot downgrade: table {table} contains fractional quantities that would be truncated to integer.")
            
    # Revert to BIGINT
    op.alter_column('paper_fills', 'quantity', type_=sa.BigInteger(), existing_type=sa.Numeric(precision=28, scale=10))
    op.alter_column('paper_orders', 'quantity', type_=sa.BigInteger(), existing_type=sa.Numeric(precision=28, scale=10))
    op.alter_column('paper_orders', 'filled_quantity', type_=sa.BigInteger(), existing_type=sa.Numeric(precision=28, scale=10))
    op.alter_column('positions', 'quantity', type_=sa.BigInteger(), existing_type=sa.Numeric(precision=28, scale=10))
