"""update_unique_constraints

Revision ID: d4ae1863048a
Revises: 23a618741eb9
"""

from collections.abc import Sequence

from alembic import op

revision: str = "d4ae1863048a"
down_revision: str | Sequence[str] | None = "23a618741eb9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_candles_stream_time"), "candles", type_="unique")
    op.create_unique_constraint(
        "uq_candles_market_time", "candles", ["provider", "symbol", "timeframe", "open_time"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_candles_market_time", "candles", type_="unique")
    op.create_unique_constraint(
        op.f("uq_candles_stream_time"),
        "candles",
        ["stream_id", "open_time"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
