"""m7_broker_portfolio_snapshots

Revision ID: db6f20ef0e19
Revises: b990f1234567
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'db6f20ef0e19'
down_revision: str | Sequence[str] | None = 'b990f1234567'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_portfolio_snapshots',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cash', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('equity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('buying_power', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('broker_positions',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider', 'symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broker_positions')
    op.drop_table('broker_portfolio_snapshots')
    # ### end Alembic commands ###
