"""m7_alpaca_paper_orders

Revision ID: ea8afad3f1d3
Revises: 0010_m5_real_image
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ea8afad3f1d3"
down_revision: str | Sequence[str] | None = "0010_m5_real_image"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:  # noqa: E501
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("paper_fills", sa.Column("broker_fill_id", sa.String(length=64), nullable=True))  # noqa: E501
    op.drop_constraint(op.f("paper_fills_order_id_key"), "paper_fills", type_="unique")  # noqa: E501
    op.create_unique_constraint("uq_paper_fills_broker_fill_id", "paper_fills", ["broker_fill_id"])  # noqa: E501
    op.add_column(
        "paper_orders",
        sa.Column("filled_quantity", sa.BigInteger(), nullable=False, server_default="0"),  # noqa: E501
    )  # noqa: E501
    op.add_column("paper_orders", sa.Column("client_order_id", sa.String(length=64), nullable=True))  # noqa: E501
    op.add_column("paper_orders", sa.Column("broker_order_id", sa.String(length=64), nullable=True))  # noqa: E501
    op.add_column("paper_orders", sa.Column("broker_status", sa.String(length=32), nullable=True))  # noqa: E501
    op.add_column(
        "paper_orders",
        sa.Column("last_reconciled_at", sa.DateTime(timezone=True), nullable=True),  # noqa: E501
    )  # noqa: E501
    op.alter_column(
        "paper_orders",
        "status",
        existing_type=sa.VARCHAR(length=16),  # noqa: E501
        type_=sa.String(length=32),  # noqa: E501
        existing_nullable=False,
    )  # noqa: E501
    op.create_unique_constraint(
        "uq_paper_orders_broker_order_id", "paper_orders", ["broker_order_id"]
    )  # noqa: E501
    op.create_unique_constraint(
        "uq_paper_orders_client_order_id", "paper_orders", ["client_order_id"]
    )  # noqa: E501
    op.drop_constraint(op.f("ck_paper_orders_state"), "paper_orders", type_="check")  # noqa: E501
    op.create_check_constraint(
        "ck_paper_orders_state_m7",
        "paper_orders",
        "side IN ('BUY','SELL') AND status IN ('SUBMITTING', 'NEW', 'ACCEPTED', 'PENDING_NEW', 'PARTIALLY_FILLED', 'FILLED', 'PENDING_CANCEL', 'CANCELED', 'REJECTED', 'EXPIRED', 'REPLACED', 'UNKNOWN') AND quantity >= 0 AND filled_quantity >= 0 AND filled_quantity <= quantity",  # noqa: E501
    )  # noqa: E501
    # ### end Alembic commands ###


def downgrade() -> None:  # noqa: E501
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_paper_orders_state_m7", "paper_orders", type_="check")  # noqa: E501
    op.create_check_constraint(
        op.f("ck_paper_orders_state"),  # noqa: E501
        "paper_orders",
        "(side::text = ANY (ARRAY['BUY'::character varying, 'SELL'::character varying]::text[])) AND (status::text = ANY (ARRAY['FILLED'::character varying, 'REJECTED'::character varying]::text[])) AND quantity >= 0",  # noqa: E501
    )  # noqa: E501
    op.drop_constraint("uq_paper_orders_client_order_id", "paper_orders", type_="unique")  # noqa: E501
    op.drop_constraint("uq_paper_orders_broker_order_id", "paper_orders", type_="unique")  # noqa: E501
    op.alter_column(
        "paper_orders",
        "status",
        existing_type=sa.String(length=32),  # noqa: E501
        type_=sa.VARCHAR(length=16),  # noqa: E501
        existing_nullable=False,
    )  # noqa: E501
    op.drop_column("paper_orders", "last_reconciled_at")  # noqa: E501
    op.drop_column("paper_orders", "broker_status")  # noqa: E501
    op.drop_column("paper_orders", "broker_order_id")  # noqa: E501
    op.drop_column("paper_orders", "client_order_id")  # noqa: E501
    op.drop_column("paper_orders", "filled_quantity")  # noqa: E501
    op.drop_constraint("uq_paper_fills_broker_fill_id", "paper_fills", type_="unique")  # noqa: E501
    op.create_unique_constraint(
        op.f("paper_fills_order_id_key"),  # noqa: E501
        "paper_fills",
        ["order_id"],
        postgresql_nulls_not_distinct=False,
    )  # noqa: E501
    op.drop_column("paper_fills", "broker_fill_id")  # noqa: E501
    # ### end Alembic commands ###
